"""
ScreenerSignal ORM Model
Records each time a stock passes the Alpha Screener criteria.
"""
from typing import Optional
from datetime import datetime
from sqlalchemy import String, Float, Integer, Boolean, Text, Date, Index, ForeignKey
from sqlalchemy.orm import Mapped, mapped_column

from app.database import Base


class ScreenerSignal(Base):
    """
    Stores each signal generated by the Alpha Screener.
    One signal per stock per screener run.
    """
    __tablename__ = "screener_signals"

    id: Mapped[int] = mapped_column(Integer, primary_key=True, autoincrement=True)
    symbol: Mapped[str] = mapped_column(String(20), nullable=False, index=True)
    company_name: Mapped[str] = mapped_column(String(200), nullable=False)
    sector: Mapped[Optional[str]] = mapped_column(String(100), nullable=True)

    # ── Signal Metadata ───────────────────────────────────────────────────────
    signal_date: Mapped[str] = mapped_column(String(10), nullable=False, index=True)  # YYYY-MM-DD
    screener_run_id: Mapped[Optional[str]] = mapped_column(String(36), nullable=True, index=True)  # UUID

    # ── Snapshot: Fundamental values at signal time ───────────────────────────
    roce: Mapped[Optional[float]] = mapped_column(Float, nullable=True)
    debt_to_equity: Mapped[Optional[float]] = mapped_column(Float, nullable=True)
    pe_ratio: Mapped[Optional[float]] = mapped_column(Float, nullable=True)
    promoter_holding: Mapped[Optional[float]] = mapped_column(Float, nullable=True)
    piotroski_f_score: Mapped[Optional[int]] = mapped_column(Integer, nullable=True)
    eps_growth_yoy: Mapped[Optional[float]] = mapped_column(Float, nullable=True)

    # ── Snapshot: Technical values at signal time ─────────────────────────────
    signal_price: Mapped[float] = mapped_column(Float, nullable=False)
    ema_200: Mapped[Optional[float]] = mapped_column(Float, nullable=True)
    ema_50: Mapped[Optional[float]] = mapped_column(Float, nullable=True)
    rsi_14: Mapped[Optional[float]] = mapped_column(Float, nullable=True)
    atr_14: Mapped[Optional[float]] = mapped_column(Float, nullable=True)
    macd: Mapped[Optional[float]] = mapped_column(Float, nullable=True)
    macd_signal: Mapped[Optional[float]] = mapped_column(Float, nullable=True)
    volume: Mapped[Optional[float]] = mapped_column(Float, nullable=True)
    avg_volume_20d: Mapped[Optional[float]] = mapped_column(Float, nullable=True)

    # ── Calculated Trade Parameters ───────────────────────────────────────────
    suggested_entry: Mapped[Optional[float]] = mapped_column(Float, nullable=True)
    suggested_sl: Mapped[Optional[float]] = mapped_column(Float, nullable=True)        # ATR-based SL
    suggested_sl_fixed: Mapped[Optional[float]] = mapped_column(Float, nullable=True)  # 5% SL
    suggested_target: Mapped[Optional[float]] = mapped_column(Float, nullable=True)    # 12% target
    risk_reward_ratio: Mapped[Optional[float]] = mapped_column(Float, nullable=True)

    # ── Filters Passed ────────────────────────────────────────────────────────
    passed_roce: Mapped[bool] = mapped_column(Boolean, default=False)
    passed_debt_to_equity: Mapped[bool] = mapped_column(Boolean, default=False)
    passed_ema_200: Mapped[bool] = mapped_column(Boolean, default=False)
    passed_rsi: Mapped[bool] = mapped_column(Boolean, default=False)
    passed_piotroski: Mapped[bool] = mapped_column(Boolean, default=False)
    passed_earnings_blackout: Mapped[bool] = mapped_column(Boolean, default=True)
    passed_all: Mapped[bool] = mapped_column(Boolean, default=False, index=True)

    # ── Phase 2: Pattern Recognition ──────────────────────────────────────────
    pattern_name: Mapped[Optional[str]] = mapped_column(String(50), nullable=True)
    pattern_confidence: Mapped[Optional[float]] = mapped_column(Float, nullable=True)
    chart_image_path: Mapped[Optional[str]] = mapped_column(String(500), nullable=True)

    # ── Status ────────────────────────────────────────────────────────────────
    is_traded: Mapped[bool] = mapped_column(Boolean, default=False)
    trade_id: Mapped[Optional[int]] = mapped_column(Integer, nullable=True)

    # Overall screener score (weighted composite)
    composite_score: Mapped[Optional[float]] = mapped_column(Float, nullable=True)

    __table_args__ = (
        Index("ix_signal_date_symbol", "signal_date", "symbol"),
        Index("ix_signal_passed", "passed_all", "signal_date"),
    )

    def __repr__(self) -> str:
        status = "✅" if self.passed_all else "❌"
        return f"<Signal {status} {self.symbol} @ ₹{self.signal_price} on {self.signal_date}>"
